from typing import List, Optional
from ..domain.entities import Period, Category, Member, Account, Transaction

class IPeriodService:
    def list_periods(self) -> List[Period]: ...
    def create_period(self, period: Period) -> Period: ...
    def delete_period(self, period_id: int) -> None: ...

class ICategoryService:
    def list_categories(self) -> List[Category]: ...
    def create_category(self, category: Category) -> Category: ...
    def delete_category(self, category_id: int) -> None: ...

class IMemberService:
    def list_members(self) -> List[Member]: ...
    def create_member(self, member: Member) -> Member: ...
    def delete_member(self, member_id: int) -> None: ...

class IAccountService:
    def list_accounts(self, period_id: int) -> List[Account]: ...
    def create_account(self, account: Account) -> Account: ...
    def delete_account(self, account_id: int) -> None: ...
    def pay_account(self, account_id: int, value: float) -> Account: ...

class ITransactionService:
    def list_transactions(self, period_id: int) -> List[Transaction]: ...
    def create_transaction(self, transaction: Transaction) -> Transaction: ...
    def delete_transaction(self, transaction_id: int) -> None: ...

class IImportService:
    def import_ofx(self, file_path: str, period_id: int) -> List[Transaction]: ...
    def import_csv(self, file_path: str, period_id: int) -> List[Transaction]: ...

class IBackupService:
    def export_json(self, period_id: int) -> str: ...
    def import_json(self, file_path: str, period_id: int) -> None: ...
