#!/bin/bash
# ============================================================
# IERS - Script de Deploy para Produção (Linux/Mac)
# ============================================================
# Plataformas: Render.com (backend) + Vercel (frontend) + Neon (DB)
# ============================================================

echo ""
echo "====================================================="
echo "  IERS - Configuração de Produção"
echo "====================================================="
echo ""
echo "Plataformas:"
echo "  Backend:  Render.com (Free Web Service)"
echo "  Frontend: Vercel (Hobby Plan)"
echo "  Banco:    Neon PostgreSQL (Free Tier)"
echo ""

echo "-----------------------------------------------------"
echo "PASSO 1: BANCO DE DADOS (Neon PostgreSQL)"
echo "-----------------------------------------------------"
echo ""
echo "1. Acesse: https://console.neon.tech"
echo "2. Crie uma conta (pode usar GitHub)"
echo "3. Crie projeto: iers-sistema | Region: US East | DB: iers_db"
echo "4. Copie a CONNECTION STRING (pooled)"
echo "   IMPORTANTE: Troque 'postgresql://' por 'postgresql+asyncpg://'"
echo ""

echo "-----------------------------------------------------"
echo "PASSO 2: BACKEND (Render.com)"
echo "-----------------------------------------------------"
echo ""
echo "1. Acesse: https://dashboard.render.com"
echo "2. New > Blueprint > Conecte repo: github.com/bife29/controle_financeiro-iers"
echo "3. render.yaml será detectado automaticamente"
echo ""
echo "Ou manualmente:"
echo "  - New > Web Service > Conecte repo"
echo "  - Root Directory: backend"
echo "  - Build: pip install -r requirements.txt && python seed.py"
echo "  - Start: uvicorn app.main:app --host 0.0.0.0 --port \$PORT"
echo "  - Plan: Free"
echo ""

echo "-----------------------------------------------------"
echo "PASSO 3: FRONTEND (Vercel)"
echo "-----------------------------------------------------"
echo ""
echo "1. Acesse: https://vercel.com"
echo "2. Add New > Project > Importe repo"
echo "3. Root Directory: frontend"
echo "4. Framework: Vite"
echo "5. Env: VITE_API_URL = https://iers-api.onrender.com"
echo ""

echo "-----------------------------------------------------"
echo "PASSO 4: VALIDAÇÃO"
echo "-----------------------------------------------------"
echo ""
echo "curl https://iers-api.onrender.com/health"
echo "Abra: https://controle-financeiro-iers.vercel.app"
echo "Login: admin@iers.org / admin123"
echo ""
echo "====================================================="
echo "  Pronto!"
echo "====================================================="
